### ISSUE TITLE
Standard ID Provider config file

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp-distro#14]
- Add a config file "com.enonic.xp.app.standardidprovider.cfg" with the following content:
````
#adminUserCreation=true
#loginWithoutUser=true
````
- Adapt the build to include this file

Linked to https://github.com/enonic/app-standardidprovider/issues/12

**Comment by sigdestad** [comment]
Glenn, what does option 1 do? I thought this was controlled by the database setting?

**Comment by GlennRicaud** [comment]
![screen shot 2018-02-20 at 14 00 22](https://user-images.githubusercontent.com/12030113/36425379-ea98bb70-1646-11e8-97f4-d72294cef7e1.png)

It is not exactly the same thing. It is one of the things I want to discuss with you when you come back. I implemented things as they were given orally, by mail or by slack but some are wrongs for me.

We should discuss the entire feature on Thursday

**Comment by GlennRicaud** [comment]
Remove adminUserCreation

Linked Github issue: https://github.com/enonic/app-standardidprovider/issues/14
