### ISSUE TITLE
Notifcations in release workflow

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-distro#148]
Every time release workflow step is finished (of default apps, XP,  xp-distro and docker) send a notification to slack channel `#release-workflow`

There are many actions to choose from
https://github.com/marketplace?type=actions&query=Slack

**Comment by jsi** [comment]
Hi Sergey!
What is the point of this task?  Just to notify when builds of release versions have been completed?
  -  I guess we now know enough about Slack to do this pretty easily, but I don't see the purpose of this.  When I do releases, I follow them through, so I have no need to see any notifications in this channel, and when the release is out, it is announced publicly and much more impactful, than a notification in a channel.

**Comment by rymsha** [comment]
It was actually requested by you - to be able to know when certain release step is finished, so you can start the next one.

**Comment by alansemenov** [comment]
@jsi what should we do with this task? It's been In progress forever. do we really need it?

**Comment by jsi** [comment]
I think this issue has come up as a misunderstanding.  Let's just close it.  Nothing has been done.
