### ISSUE TITLE
Publish to global repositories

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-distro#158]
Dependabot doesn't find updates for xp and libs. That is because it seeks only in global repositories. (Used to support custom ones, but not anymore)
It will also improve availability for users (in times when our public repo is down)

Probably easiest is to configure sync from our public repo.
Maybe start with jcenter only and see how it goes?

Need to publish
com.enonic.xp jars (strictly speaking, only -api jars)
com.enonic.xp.lib jars
com.enonic.lib jars

**Comment by rymsha** [comment]
jcenter is dead. Focus on maven central

**Comment by jsi** [comment]
Here is the guide for how to publish to Maven Central: https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by rymsha** [comment]
Maybe this could work? https://www.jfrog.com/confluence/display/JFROG/Repository+Replication

**Comment by jsi** [comment]
I'll check it out.  -  Thanks.

**Comment by rymsha** [comment]
`repositories` is only for reading, not publishing

**Comment by jsi** [comment]
So, where is the publishing definition that publishes to enonicRepo?

The maven-publish plugin is added, but I don't see any configuration of it.

**Comment by jsi** [comment]
Replication with Artifactory seems a no-go: Maven Central is Sonatype, and the doc you sent me clearly states:

**We strongly recommend that replication is only performed between servers running the same version of Artifactory Pro.**
