### ISSUE TITLE
Snapshot builds on branches fail

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#178]
Snapshots have not been built correctly on the 7.7 branch since June 11th, when the 7.7.1-SNAPSHOT was built last:
https://repo.enonic.com/dev/com/enonic/xp/enonic-xp-generic/

**Comment by rymsha** [comment]
lack of https://github.com/actions/runner/issues/409 makes things slightly more complicated

**Comment by rymsha** [comment]
system application builds were not triggering xp-distro 7.7 branch, but instead only master branch was rebuilt.
Similarly system applications were built on master branch only in case of XP 7.7 branch changes.
Both aspects fixed.

In addition to that:
- concurrency was corrected in all repositories, so repository_dispatch builds respect github ref from payload
- Similar problem between CS and lib-admin-ui corrected as well
