### ISSUE TITLE
Set up testing environment for OWASP testing of the self-service cloud environment.

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#182]
It has been suggested that the QA environment may be used.

Kick-off meeting called for January 3rd.

**Comment by gbbirkisson** [comment]
What is the task here exactly? @jsi

**Comment by jsi** [comment]
It is everything we agreed to in the meeting with Encripto, Friday the 7th.  -  I believe you have already done all that is needed, so I just added you to the task, since it is you who have done the work.

**Comment by gbbirkisson** [comment]
I thought this was related to the Encrypto testing that was done earlier this winter, that's why I closed it.

**Comment by jsi** [comment]
Oh.  Sorry.  You are right.  Since it was closed today, I took it for granted that it was related to the new test that finished on Friday.But, all issues in these projects shou
