### ISSUE TITLE
Stop publishing test-reports to repo.

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#208]
After the switch to run all tests on every commit, test-reports are published to GitHub.
But they are still also published to our repo, where they make a big mess, overwriting each other because they all have the same name.

We need to stop publishing to our repo, since the test reports are never accessed from there, and to stop the mess.

**Comment by rymsha** [comment]
I _hope_ I hade done it for master branches. 7.8 branches may still be affected, but hopefully we won't release 7.8.x versions anymore.

**Comment by jsi** [comment]
Okay, then we delete this issue.  The problem was on the 7.8 branch.
