### ISSUE TITLE
Migrate to GraalVM

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-distro#218]
GraalVM has an embedded GraalJS that gives significant performance boost in [some cases](https://github.com/enonic/lib-react4xp/issues/455)

At the same time GraalVM is based on OpenJDK 11 and should work out of the box with existing XP.

Since plan is to replace deprecated Nashorn with Graal.JS anyway, it is better to start the migration sooner than XP 8.

**Comment by rymsha** [comment]
The biggest complexity is, probably, the use of GraalVM docker images (https://github.com/graalvm/container/pkgs/container/graalvm-ce) instead of OpenJDK ones on hub.docker.com

**Comment by gbbirkisson** [comment]
The implications of changing our current base image to that new image:
- They are based on different distros, old is Ubuntu and new is Oracle Linux (RHEL). That changes most of the build process.
- New base image does not support all architectures that we support now (but arm64 and amd64 seems to be supported).

Alternative is to find (or create) a graalvm ubuntu image. That will simplify the build but probably introduce technical dept down the line.

**Comment by sigdestad** [comment]
It would be nice to get some input on how much work would go into building our own docker base image (i.e. GraalVM + Ubuntu) vs changing our build process. 

As this is a feature release (7.10) Keeping current build process and avoiding changes for customers would be a strongly preferable.

**Comment by rymsha** [comment]
support of s390x ppc64 and armv7 - is just a joke (I hope).

**Comment by jsi** [comment]
I have run some tests with the regular 7.10.0-SNAPSHOT image for Mac (https://repo.enonic.com/service/rest/repository/browse/dev/com/enonic/xp/enonic-xp-mac-sdk/7.10.0-SNAPSHOT/), and it is very obvious that previews of for instance the pages in SuperHero or Image Expert are much faster than before.  On the other hand, loading of large images seems to take about the same time, which obviously makes a lot of sense, considering it is the JavaScript engine that is faster and nothing else.  -  Will continue Mac-specific testing with Slava tomrorrow.

**Comment by sigdestad** [comment]
Surprised if superhero and image expert are faster, since we are still using Nashorn there AFAIK? Does GraalVM improve Nashorn performance as well?

**Comment by jsi** [comment]
Well, I don't know, but do these apps require Nashorn?  If they are just written in JavaScript, don't they use the engine available?

I do not know, but now I just did a simple comparison test between 7.9.2 (without Graal) and 7.10.0-SNAPSHOT (with graal) on my local machine, and it is very obvious:  The first time I click on the front page or any of the posts in SuperHero, the loading icon circles 5 or 6 times with 7.9.2, but only about 2 times with 7.10.0.  If I go on to click on other posts, they appear almost instantly on 7.10.0, while I still see something like a half to a whole rotation of the loading icon with 7.9.2, sorry that this is not more scientific, but it is so obvious, more detailed science is not necessary. 😜

**Comment by rymsha** [comment]
Thomas is right, Superhero still uses Nashorn even on GraalVM. For now only react4xp based apps using SSR can benefit from new JS engine.

This performance improvement may easily be an effect of something else. 
GraalVM Community Edition may be more performant than stock OpenJDK, but may be worse in some cases, too.

**Comment by sigdestad** [comment]
Could it be that the new Graal compiler is so much better than old JIT?

**Comment by rymsha** [comment]
For me it looks like Superhero performance is the same.
