### ISSUE TITLE
Add missing Spanish translations

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#27]
The following phrase-codes are not translated to Spanish:

*lib-admin-ui* : notify.fileExists, tooltip.xdata.enable, tooltip.xdata.disable, dialog.search.matchcyclic

*app-applications* : field.tools, field.widgets, field.extensions

*app-contentstudio* : field.sortType.ascending, dialog.publish.readOnlyError, field.noOpenIssues, tooltip.sortType.ascending, field.sortType.publish, field.preview.toolbar.status, field.sortType.created, field.openIssues, dialog.duplicate.dependants, tooltip.sortType.descending, field.sortType.modified, action.editFragment, field.sortType.displayName, field.sortType.descending

*app-users* : notify.invalid.idProviderConfig

**Comment by aro** [comment]
https://github.com/enonic/app-users/commit/d6f69be8a3f805c54d0593242376133c27db339f
https://github.com/enonic/app-contentstudio/commit/37b4d3c283a3047aef0b2d2503efbb9a5d393f09
https://github.com/enonic/app-applications/commit/0e46016b52668cd4302bf5f0ba682e46327af41b
https://github.com/enonic/lib-admin-ui/commit/c099203205b7775804b7f5051c15625a5ffab19d
