### ISSUE TITLE
Add missing Swedish translations

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#29]
The following phrase-codes have not been translated to Swedish:

*lib-admin-ui* : notify.fileExists, tooltip.xdata.enable, tooltip.xdata.disable, dialog.search.matchcyclic

*app-applications* : field.tools, field.widgets, field.extensions

*app-contentstudio* : field.sortType.ascending, dialog.publish.readOnlyError, field.noOpenIssues, tooltip.sortType.ascending, field.sortType.publish, field.preview.toolbar.status, field.sortType.created, field.openIssues, dialog.duplicate.dependants, tooltip.sortType.descending, field.sortType.modified, action.editFragment, field.sortType.displayName, field.sortType.descending

*app-users* : notify.invalid.idProviderConfig

**Comment by Bellfalasch** [comment]
Done and commited to master for each app.
