### ISSUE TITLE
Embedding JDK 11

### ISSUE THREAD

**Issue by aro** [enonic/xp-distro#48]
Update the build to download and include JDK 11 in the distribution.

The JDK is platform specific (Windows, Linux, Mac), so the build will generate a distribution for a specific platform. 

The target platform can be configured with a parameter, by default it will build the generic distro without JDK, as before.

- Build the **generic** distro, without JDK: 
`gradlew build`

- Build the distro for **Windows** with emebedded JDK: 
`gradlew build -Pplatform=windows`

- Build the distro for **Mac** with emebedded JDK: 
`gradlew build -Pplatform=mac`

- Build the distro for **Linux** with emebedded JDK: 
`gradlew build -Pplatform=linux`

- Build the distro for the **current** running platform: 
`gradlew build -Pplatform=current`

----
When a JDK platform is specified, the following additional steps will be done:
- Download the requested JDK, from ~http://jdk.java.net/11/~ https://adoptopenjdk.net
- Unpack the JDK
- Move the JDK files to ```/jdk``` inside XP distribution
- Update setenv.sh and setenv.bat scripts to setup JAVA_HOME (they are called by server.sh, server.bat)

**Comment by aro** [comment]
There is a site providing binaries for the different platforms:  https://adoptopenjdk.net

They even have a REST API to get the list of versions (release, nightly builds,..) with links to download:

  https://api.adoptopenjdk.net/v2/info/releases/openjdk11

Consider fetching the JDK distributions from [AdoptOpenJDK](https://adoptopenjdk.net/about.html).

**Comment by GlennRicaud** [comment]
Storing the info about the size diff:
Generic distro: 108 MiB
Distro with Mac JDK: 290 MiB
