### ISSUE TITLE
XP Distro - JDK options

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp-distro#53]
Instead of a single property 'platform', add the possibility to have 3 properties:
- os //windows, linux, mac, current. Defaults to current
- arch //x64, x32. Defaults to x64
- type //jdk, jre, generic. Defaults to generic

**Comment by aro** [comment]
The size of the JRE distro is about half the size of the JDK distro:

109M distro-7.0.0-SNAPSHOT.zip
296M distro-linux-jdk-7.0.0-SNAPSHOT.zip
149M distro-linux-jre-7.0.0-SNAPSHOT.zip
291M distro-mac-jdk-7.0.0-SNAPSHOT.zip
145M distro-mac-jre-7.0.0-SNAPSHOT.zip
318M distro-windows-jdk-7.0.0-SNAPSHOT.zip
174M distro-windows-jre-7.0.0-SNAPSHOT.zip
