### ISSUE TITLE
Translate missing phrases to French

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#69]
Enonic XP:
The following keys are missing in 'phrases_fr.properties': [style.editor.original, media.image.altText.label]

Applications App:
The following keys are missing in 'phrases_fr.properties': [field.idProviderApplications, field.installed]

Users App:
The following keys are missing in 'phrases_fr.properties': [field.report.generated, notify.report.finished, field.report, notify.invalid.application, action.report.generate, action.report.download, field.idProvider, notify.delete.idprovider.multiple, notify.delete.idprovider.single, field.application, field.repository.select, field.transitiveMemberships]

Lib Admin UI:
The following keys are missing in 'common_fr.properties': [field.progress.applying, dialog.confirm.title, dialog.confirm.occurrences.delete, dialog.newContent.pathDescription, editor.dblclicktoedit, dialog.confirm.occurrences.title]

**Comment by GlennRicaud** [comment]
https://github.com/enonic/xp/commit/ad45fe8bd3e2cfba1d1a9bc6f55294f35765dba3
https://github.com/enonic/app-applications/commit/c9b9c5e1252f6c490af064f0f6d03126c5c2cbde
https://github.com/enonic/app-users/commit/2b82a85207020ac76f9411001b7860a81a1d6182
https://github.com/enonic/lib-admin-ui/commit/d9bdddbfb6d7d42840ade7433b749370489656b3
