### ISSUE TITLE
Translate missing phrases to Swedish

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#74]
Enonic XP: https://github.com/enonic/xp/tree/master/modules/app/app-system/src/main/resources/i18n
The following keys are missing in 'phrases_sv.properties': 
```
 - media.image.altText.label
 - style.editor.original
```

Applications App: https://github.com/enonic/app-applications/tree/master/src/main/resources/i18n
The following keys are missing in 'phrases_sv.properties': 
```
 - field.idProviderApplications
 - field.installed
```

Users App: https://github.com/enonic/app-users/tree/master/src/main/resources/i18n
The following keys are missing in 'phrases_sv.properties': 
```
 - action.report.download
 - action.report.generate
 - field.application
 - field.idProvider
 - field.report
 - field.report.generated
 - field.repository.select
 - field.transitiveMemberships
 - notify.delete.idprovider.multiple
 - notify.delete.idprovider.single
 - notify.invalid.application
 - notify.report.finished
```

Lib Admin UI: https://github.com/enonic/lib-admin-ui/tree/master/src/main/resources/i18n
The following keys are missing in 'common_sv.properties': 
```
 - dialog.confirm.occurrences.delete
 - dialog.confirm.occurrences.title
 - editor.dblclicktoedit
 - field.progress.applying
```

**Comment by Bellfalasch** [comment]
**Enonic XP:**
The following keys are missing in 'phrases_sv.properties':

style.editor.original = 
media.image.altText.label = 

**Applications App:**
The following keys are missing in 'phrases_sv.properties':

field.idProviderApplications = 
field.installed = 

**Users App:**
The following keys are missing in 'phrases_sv.properties':

field.report.generated = 
notify.report.finished = 
field.report = 
notify.invalid.application = 
action.report.generate = 
action.report.download = 
field.idProvider = 
notify.delete.idprovider.multiple = 
notify.delete.idprovider.single = 
field.application = 
field.repository.select = 
field.transitiveMemberships = 

**Lib Admin UI:**
The following keys are missing in 'common_sv.properties':

field.progress.applying = 
dialog.confirm.occurrences.delete = 
editor.dblclicktoedit = 
dialog.confirm.occurrences.title]

**Comment by Bellfalasch** [comment]
These files? @jsi 
https://github.com/enonic/xp-distro/tree/master/modules/distro/src/home/config
(User's app is now known as standard ID provider right?)
Should there be even more files, and where do I find those?

**Comment by jsi** [comment]
Sorry, Bobby.  I thought you knew your way around.  -  I have updated the description of the task now, including GitHub links to the files.  Hope that helps.  The list now reflects what is missing from the master branch of each project.  If anything was committed to another branch, I will have missed that.

**Comment by Bellfalasch** [comment]
Thanks JSI =) I'm not very used to working inside XP core, it's too far apart each time I do, and this time a lot have changed too. But thanks for the links, most brilliant! Will translate and create PR now.

**Comment by Bellfalasch** [comment]
Looks like no PR was needed, merged straight into master. All files updated.
