### ISSUE TITLE
Linux distribution should be tar.gz

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-distro#85]
Currently it is zip and execution flag for sh files is lost

**Comment by edloidas** [comment]
@jsi @rymsha What about the publications? Should we [keep ZIP extension](https://github.com/enonic/xp-distro/blob/e42f74ffee0089818b062302021cb0fd2309860b/build.gradle#L161-L168) when publishing the artifact?

**Comment by rymsha** [comment]
I think we have to distribute both `zip` and `tar.gz` at least until version 8, unfortunately. And drop `zip` linux distribution of XP 8

Don't forget into looking into deb and rpm distributions as well.
