### ISSUE TITLE
Don't provide JRE bundle as it is confusing.

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-distro#86]
Read here about JRE/JDK https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html

We should reconsider what distros we build.

**Comment by rymsha** [comment]
Apparently there is "JRE" sometimes and we are using such exception. https://adoptopenjdk.net/releases.html

The benefits of having JRE and JDK are quite low though. For use it is extra configuration + 40 * 3 MB per build.

**Comment by rymsha** [comment]
as an example Elasticsearch bundles full JDK.

**Comment by sigdestad** [comment]
120Mb per build?

**Comment by rymsha** [comment]
Most likely per release. I better not mentioned size as an argument.
I just want users to be less confused :)

But... docker image uses stripped "server" version. 
So size of docker image will increase if we blindly put full JDK everywhere.

At the same time I don't agree java in docker should come from distro. https://hub.docker.com/_/openjdk/ is there for us!

**Comment by rymsha** [comment]
More concrete:
I propose
- Drop server distro starting from xp 8.
- Docker image shoud be based on the one with jdk (or compose it)
