### ISSUE TITLE
serviced support

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-distro#87]
For instance, setting up a service on Fedora 30 is not that simple.

**Comment by jsi** [comment]
When this issue is implemented, it should be followed by documentation.  We do not have very good operations doc for 7.x, but it would improve greatly if this guide is written: https://github.com/enonic/doc-xp/issues/94

**Comment by anatol-sialitski** [comment]
Issue moved to [enonic/xp #8492](https://github.com/enonic/xp/issues/8492) via [**ZenHub**](https://www.zenhub.com/)
