### ISSUE TITLE
Research GitHub Packages as a new repo

### ISSUE THREAD

**Issue by jsi** [enonic/xp-distro#95]
- Is it possible to move our entire old repo into Packages?
- Who is using Artifactory API and how?  (CLI, market, Gradle plugin, old enonic download)
- How does pricing work?
- What can we put there?  Only our own things?
- Mix and match private and public?

**Comment by edloidas** [comment]
GitHub Packages
===

# [About GitHub Packages](https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages)

* [GitHub Packages Feature](https://github.com/features/packages)

* You can publish packages in a public repository (public packages) to share with all of GitHub, or in a private repository (private packages) to share with collaborators or an organization. You can use GitHub roles and teams to limit who can install or publish each package, as packages inherit the permissions of the repository.

* You need an access token to publish, install, and delete packages in GitHub Packages. You can use a personal access token to authenticate with your username directly to GitHub Packages or the GitHub API. You can use a GITHUB_TOKEN to authenticate using a GitHub Actions workflow.

## [Pricing & Billing](https://github.com/pricing#feature-comparison)

* GitHub Packages usage is free for public packages. For private packages, each GitHub account receives a certain amount of free storage and data transfer, depending on the product used with the account. By default, your account will have a spending limit of $0, which prevents additional usage of storage or data transfer after you reach the included amounts. If you increase your spending limit above the default of $0, you will be billed for any additional storage or data transfer, also called overages, up to your spending limit. For more information, see "[About billing for GitHub Packages](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages)."
* Traffic is only counted outside GitHub Actions. We may need to switch to this CI.
* All other data transferred out from private packages, such as for local builds, is not free.
* Storage usage is shared with build artifacts produced by GitHub Actions for repositories owned by your account. For more information, see "[About billing for GitHub Actions](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions)."
* GitHub Team plan may not be enough.
* We are already paying for GitHub Team plan.
* There are 21 members and 4 contributors.

## Package Clients

| Package client | Language   | Package format | Description |
|----------------|------------|----------------|-------------|
| npm            | JavaScript | `package.json` | Node package manager |
| gem            | Ruby       | `Gemfile`      | RubyGems package manager |
| mvn            | Java       | `pom.xml`      | Apache Maven project management and comprehension tool |
| gradle         | Java       | `build.gradle` or `build.gradle.kts` | Gradle build automation tool for Java |
| docker         | N/A        | `Dockerfile`   | Docker container management platform |
| dotnet CLI     | .NET       | `nupkg`        | NuGet package management for .NET |

## [Publishing Package](https://help.github.com/en/github/managing-packages-with-github-packages/publishing-a-package)

> See [@Codertocat/hello-world-npm](https://github.com/Codertocat/hello-world-npm/packages/10696?version=1.0.1) for package example.

# FAQ

__Q:__ Is it possible to move our entire old repo into Packages?
__A:__ Only manually and it's a big piec of work.

__Q:__ Who is using Artifactory API and how? (CLI, market, Gradle plugin, old enonic download)
__A:__ --

__Q:__ How does pricing work?
__A:__ See the "Pricing & Billing" section.

__Q:__ What can we put there? Only our own things?
__A:__ Everything.

__Q:__ Mix and match private and public?
__A:__ Yes, you can. To upload and download packages from GitHub you need to configure your tools, be authenticated and have rights to do interact with the repository, that package belongs to. As for the billing, you will only pay for the private repos.

---

__Q:__ Where can I find the list of packages?
__A:__ Under the organization's [Packages](https://github.com/orgs/enonic/packages) tab.

__Q:__ Does the GitHub has the API to work with packages?
__A:__ Yes, it does have the [API](https://developer.github.com/v4/guides/forming-calls/). Here is a user [example](https://github.community/t5/GitHub-Actions/how-to-list-packages-and-versions-in-github-package-registry/td-p/39155) of listing all the packages from the regestry.

**Comment by edloidas** [comment]
GitHub Packages
===

# Pros
* Fits into the GitHub-only workflow.
* Easy to set up and publish. We don't need to change much to make things work.

# Cons
- Installing packages from the registry requires [authentification](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-gradle-for-use-with-github-packages#installing-a-package) to GitHub Packages with a username and [token](https://github.com/settings/tokens);
- Published packages can't be updated or removed;
- Packages can be accessed by the direct URL or from the package page, that resembles one from the npm. That's quite different from the approach, used by Artifactory and access to files in FTP-like style.

**Comment by edloidas** [comment]
* Can we remove the third-party libraries from our Enonic repo? We have Apache and other bundles stored there, that we may not use. All that stuff is available from public repositories.
* Can we move to the GitHub Packages only for the new versions, leaving old versions in the old repo?

**Comment by jsi** [comment]
It seems to me that it may be slightly too early to switch to GitHub Packages.  But starting to use it with the goal of switching when we are ready, for instance in a year, would be a good thing.  This will give us the following:
- GitHub Packages get another year to mature.
- We get a year to learn it before we make a final decision, learning what the discovered obstacles may be and how to overcome them without a strict hard limit before we have to close Artifactory in a stressful period.

**Comment by jsi** [comment]
Great work here.  Seems the Cons are too many, so for now, we are just staying with our current solution of operating Artifactory ourselves.  Turned out to be some simpler ways of doing it.
